/** Console autonome : aucune donnée n'est incluse dans le HTML public. */
export function adminDashboardHtml(): string {
  return `<!doctype html>
<html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>FloraPin — Supervision</title>
<style>
:root{color-scheme:dark;--bg:#0c1511;--panel:#14221b;--line:#294235;--text:#edf7f0;--muted:#9bb2a5;--accent:#7ed69c;--danger:#ff9b91}
*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at top,#183126,var(--bg) 42%);color:var(--text);font:15px system-ui,sans-serif;min-height:100vh}
main{max-width:1280px;margin:auto;padding:28px}header{display:flex;gap:18px;justify-content:space-between;align-items:center;margin-bottom:24px}h1,h2,p{margin:0}h1{font-size:clamp(25px,4vw,38px)}h2{font-size:18px;margin-bottom:14px}.muted,small{color:var(--muted)}
button,input{font:inherit;border-radius:10px;border:1px solid var(--line);padding:10px 13px}button{background:#254b37;color:var(--text);cursor:pointer}button:hover{background:#326149}button:disabled{opacity:.45;cursor:not-allowed}input{background:#0d1812;color:var(--text);min-width:280px}.panel{background:color-mix(in srgb,var(--panel) 94%,transparent);border:1px solid var(--line);border-radius:16px;padding:18px;box-shadow:0 12px 35px #0004}
#login{max-width:520px;margin:15vh auto}.login-row{display:flex;gap:10px;margin-top:18px}.login-row input{flex:1}.hidden{display:none!important}.top-actions{display:flex;gap:10px;align-items:center}.status{width:10px;height:10px;border-radius:50%;background:var(--accent);box-shadow:0 0 12px var(--accent)}
.metrics{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:12px;margin-bottom:18px}.metric strong{display:block;font-size:28px;margin-top:5px}.layout{display:grid;grid-template-columns:1fr 1fr;gap:18px;margin-bottom:18px}.table-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:8px}.table-stat{display:flex;justify-content:space-between;padding:10px;background:#0e1b15;border-radius:9px}
table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:9px;border-bottom:1px solid var(--line);font-size:13px}th{color:var(--muted)}.scroll{overflow:auto}.gallery{display:grid;grid-template-columns:repeat(auto-fill,minmax(190px,1fr));gap:14px}.image-card{overflow:hidden;padding:0}.image-card img,.placeholder{width:100%;aspect-ratio:4/3;object-fit:cover;background:#09100c;display:grid;place-items:center}.image-meta{padding:12px}.image-meta strong,.image-meta small{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.pager{display:flex;justify-content:center;align-items:center;gap:14px;margin-top:18px}.error{color:var(--danger);margin-top:12px}.section-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:14px}.section-head h2{margin:0}
.log-list{display:grid;gap:10px}.log-card{background:#0e1b15;border:1px solid var(--line);border-radius:11px;padding:13px}.log-head{display:flex;justify-content:space-between;gap:14px;align-items:flex-start}.log-head strong,.log-head small{display:block}.log-tags{display:flex;flex-wrap:wrap;gap:6px;margin:9px 0}.tag{padding:4px 8px;border-radius:99px;background:#213b2d;color:var(--muted);font-size:12px}.tag.error-tag{background:#4a2928;color:#ffc3bd}details{margin-top:8px}summary{cursor:pointer;color:var(--accent)}pre{white-space:pre-wrap;overflow-wrap:anywhere;max-height:420px;overflow:auto;padding:12px;border-radius:9px;background:#09100c;color:#cce5d4;font:12px ui-monospace,monospace}
@media(max-width:760px){main{padding:16px}.layout{grid-template-columns:1fr}header{align-items:flex-start;flex-direction:column}.login-row{flex-direction:column}input{min-width:0;width:100%}.top-actions{width:100%;justify-content:space-between}}
</style></head><body><main>
<section id="login" class="panel"><h1>🌿 FloraPin</h1><p class="muted">Console de supervision du serveur</p><div class="login-row"><input id="token" type="password" autocomplete="current-password" placeholder="Jeton d’administration" aria-label="Jeton d’administration"><button id="connect">Ouvrir</button></div><p id="loginError" class="error" role="alert"></p></section>
<section id="dashboard" class="hidden"><header><div><h1>Supervision FloraPin</h1><p class="muted">Données serveur et inventaire des médias</p></div><div class="top-actions"><span class="status" aria-label="Serveur joignable"></span><small id="updated"></small><button id="refresh">Actualiser</button><button id="logout">Fermer</button></div></header>
<div id="metrics" class="metrics"></div>
<div class="layout"><section class="panel"><h2>Volumes de données</h2><div id="tables" class="table-grid"></div></section><section class="panel"><h2>Derniers comptes</h2><div class="scroll"><table><thead><tr><th>Nom</th><th>Email</th><th>Vérifié</th><th>Création</th></tr></thead><tbody id="users"></tbody></table></div></section></div>
<section class="panel" style="margin-bottom:18px"><h2>Dernières fleurs synchronisées</h2><div class="scroll"><table><thead><tr><th>Espèce</th><th>Propriétaire</th><th>Visibilité</th><th>À identifier</th><th>Création</th></tr></thead><tbody id="flowers"></tbody></table></div></section>
<section class="panel" style="margin-bottom:18px"><div class="section-head"><div><h2>Journaux envoyés par les utilisateurs</h2><small id="logCount"></small></div></div><div id="clientLogs" class="log-list"></div><div class="pager"><button id="logsPrev">Précédent</button><span id="logsPage"></span><button id="logsNext">Suivant</button></div></section>
<section class="panel"><div class="section-head"><div><h2>Inventaire des images</h2><small id="imageCount"></small></div></div><div id="gallery" class="gallery"></div><div class="pager"><button id="prev">Précédent</button><span id="page"></span><button id="next">Suivant</button></div></section>
<p id="dashboardError" class="error" role="alert"></p></section></main>
<script>
const state={token:sessionStorage.getItem('florapinAdminToken')||'',page:1,totalPages:1,logsPage:1,logsTotalPages:1};
const $=id=>document.getElementById(id);const fmt=n=>new Intl.NumberFormat('fr-FR').format(n||0);const date=v=>v?new Date(v).toLocaleString('fr-FR'):'—';
const api=(path)=>fetch(new URL(path,location.href),{headers:{'x-admin-token':state.token}}).then(async r=>{if(!r.ok)throw new Error((await r.json().catch(()=>({}))).message||('Erreur '+r.status));return r.json()});
function cell(row,value){const td=document.createElement('td');td.textContent=value;row.append(td)}
function metric(label,value){const d=document.createElement('div');d.className='panel metric';const s=document.createElement('small');s.textContent=label;const b=document.createElement('strong');b.textContent=value;d.append(s,b);return d}
async function loadOverview(){const d=await api('overview');$('updated').textContent='Mis à jour '+date(d.generatedAt);$('metrics').replaceChildren(metric('Utilisateurs',fmt(d.tables.users)),metric('Fleurs',fmt(d.tables.flowers)),metric('Images référencées',fmt(d.tables.flowers+d.tables.flower_photos)),metric('Base PostgreSQL',(d.database.sizeBytes/1048576).toFixed(1)+' Mo'),metric('Connexions DB',fmt(d.database.connections)),metric('Uptime',Math.floor(d.uptimeSeconds/3600)+' h'));
$('tables').replaceChildren(...Object.entries(d.tables).map(([name,count])=>{const e=document.createElement('div');e.className='table-stat';const n=document.createElement('span');n.textContent=name;const c=document.createElement('strong');c.textContent=fmt(count);e.append(n,c);return e}));
$('users').replaceChildren(...d.recentUsers.map(u=>{const r=document.createElement('tr');cell(r,u.displayName);cell(r,u.email);cell(r,u.emailVerified?'Oui':'Non');cell(r,date(u.createdAt));return r}));
$('flowers').replaceChildren(...d.recentFlowers.map(f=>{const r=document.createElement('tr');cell(r,f.species||'Non identifiée');cell(r,f.ownerName);cell(r,f.visibility);cell(r,f.needsIdentification?'Oui':'Non');cell(r,date(f.createdAt));return r}));}
async function loadImages(){const d=await api('images?page='+state.page+'&pageSize=24');state.totalPages=d.totalPages;$('imageCount').textContent=fmt(d.total)+' objets image';$('page').textContent='Page '+d.page+' / '+d.totalPages;$('prev').disabled=d.page<=1;$('next').disabled=d.page>=d.totalPages;
$('gallery').replaceChildren(...d.items.map(i=>{const card=document.createElement('article');card.className='panel image-card';let media;if(i.previewUrl){media=document.createElement('img');media.src=i.previewUrl;media.loading='lazy';media.alt=i.label||i.kind;if(i.originalUrl){const link=document.createElement('a');link.href=i.originalUrl;link.target='_blank';link.rel='noopener';link.append(media);media=link}}else{media=document.createElement('div');media.className='placeholder';media.textContent='Image indisponible'}const meta=document.createElement('div');meta.className='image-meta';const title=document.createElement('strong');title.textContent=i.label||i.kind;const owner=document.createElement('small');owner.textContent=i.ownerName+' · '+i.kind;const key=document.createElement('small');key.title=i.imageKey;key.textContent=i.imageKey;meta.append(title,owner,key);card.append(media,meta);return card}));}
function tag(value,error){const e=document.createElement('span');e.className='tag'+(error?' error-tag':'');e.textContent=value;return e}
async function loadClientLogs(){const d=await api('client-logs?page='+state.logsPage+'&pageSize=12');state.logsTotalPages=d.totalPages;$('logCount').textContent=fmt(d.total)+' rapport'+(d.total>1?'s':'');$('logsPage').textContent='Page '+d.page+' / '+d.totalPages;$('logsPrev').disabled=d.page<=1;$('logsNext').disabled=d.page>=d.totalPages;
$('clientLogs').replaceChildren(...d.items.map(i=>{const card=document.createElement('article');card.className='log-card';const head=document.createElement('div');head.className='log-head';const identity=document.createElement('div');const name=document.createElement('strong');name.textContent=i.displayName;const email=document.createElement('small');email.textContent=i.email;identity.append(name,email);const sent=document.createElement('small');sent.textContent=date(i.createdAt);head.append(identity,sent);const tags=document.createElement('div');tags.className='log-tags';tags.append(tag('App '+i.appVersion+' ('+i.versionCode+')'),tag(i.deviceModel),tag('Android '+i.androidVersion),tag(i.locale),tag('Sync '+i.syncStatus,i.syncStatus==='ERROR'));if(i.syncError)tags.append(tag(i.syncError,true));const details=document.createElement('details');const summary=document.createElement('summary');summary.textContent='Afficher le journal technique';const pre=document.createElement('pre');pre.textContent=i.logs;details.append(summary,pre);card.append(head,tags,details);return card}));}
async function load(){try{$('dashboardError').textContent='';await Promise.all([loadOverview(),loadImages(),loadClientLogs()]);$('login').classList.add('hidden');$('dashboard').classList.remove('hidden')}catch(e){$('dashboardError').textContent=e.message;throw e}}
async function connect(){state.token=$('token').value.trim();$('loginError').textContent='';try{await load();sessionStorage.setItem('florapinAdminToken',state.token)}catch(e){$('loginError').textContent=e.message;$('dashboard').classList.add('hidden');$('login').classList.remove('hidden')}}
$('connect').onclick=connect;$('token').onkeydown=e=>{if(e.key==='Enter')connect()};$('refresh').onclick=()=>load().catch(()=>{});$('logout').onclick=()=>{sessionStorage.removeItem('florapinAdminToken');location.reload()};$('prev').onclick=()=>{state.page--;loadImages().catch(e=>$('dashboardError').textContent=e.message)};$('next').onclick=()=>{state.page++;loadImages().catch(e=>$('dashboardError').textContent=e.message)};$('logsPrev').onclick=()=>{state.logsPage--;loadClientLogs().catch(e=>$('dashboardError').textContent=e.message)};$('logsNext').onclick=()=>{state.logsPage++;loadClientLogs().catch(e=>$('dashboardError').textContent=e.message)};
if(state.token){$('token').value=state.token;connect()}setInterval(()=>{if(!$('dashboard').classList.contains('hidden'))loadOverview().catch(e=>$('dashboardError').textContent=e.message)},30000);
</script></body></html>`;
}
